apiVersion: v1
kind: Pod
metadata:
  name: spark-job2-structured-streaming
  namespace: default
  labels:
    app: spotify-platform
    job: spark-job2
spec:
  restartPolicy: Never
  containers:
    - name: spark-job2
      image: public.ecr.aws/bitnami/spark:3.5
      command:
        - "spark-submit"
      args:
        - "--master"
        - "spark://spark-master:7077"
        - "--packages"
        - "org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0"
        - "--jars"
        - "/opt/spark-jobs/jars/postgresql-42.7.1.jar"
        - "/opt/spark-jobs/job2_structured_streaming.py"
      env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: spotify-secrets
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: spotify-secrets
              key: postgres-password
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        - name: KAFKA_TOPIC
          value: "spotify.play_events"
        - name: SPARK_POSTGRES_JDBC_URL
          value: "jdbc:postgresql://postgres:5432/spotify_platform"
      volumeMounts:
        - name: spark-jobs
          mountPath: /opt/spark-jobs
        - name: checkpoints
          mountPath: /tmp/spark_checkpoints
      resources:
        requests:
          cpu: "500m"
          memory: "2Gi"
        limits:
          cpu: "2"
          memory: "4Gi"
  volumes:
    - name: spark-jobs
      hostPath:
        path: /opt/spark-jobs
    - name: checkpoints
      emptyDir: {}
